---

- hosts: masters[0]
  gather_facts: true
  become: yes
  vars_files:
    - ./vars/base_vars.yaml
  tasks:
    - name: create folders
      file:
        path: "/home/{{ os_admin_username }}/k8s_addons/ingress"
        state: directory
        mode: '0644'

    - name: create kubernetes services ingress manifests
      template:
        src: ./templates/k8s_ingress_manifest.yaml.j2
        dest: "/home/{{ os_admin_username }}/k8s_addons/ingress/k8s_ingress_manifest.yaml"
        mode: '0644'

    - name: Apply Ingress manifests
      kubernetes.core.k8s:
        kubeconfig: "/etc/kubernetes/admin.conf"
        state: present
        src: "{{ item }}"
      loop:
        - "/home/{{ os_admin_username }}/k8s_addons/ingress/k8s_ingress_manifest.yaml"
  


