# code: language=ansible
---
- hosts: masters:workers
  become: false
  gather_facts: false
  tasks:
    - name: Check all hosts contain /dev/sdb, /dev/sdc
      ansible.builtin.stat:
        path: "{{ item}}"
      loop:
        - /dev/sdb
        - /dev/sdc
      register: st
      until: st.stat.exists == true
      retries: 150
      delay: 10

    - name: Fail if the file does not belong to 'root'
      debug:
        msg: "Assuming all additional disks attached to vms"

- name: "Configure LVMs, FSes and mount them"
  hosts: masters:workers # for sure all hosts
  become: yes
  vars:
    configure_lvm_and_fs_storages:
      - disk: sdb
        vg_name: data1_vg
        lvm_name: data1_lv
        fs_type: ext4
        mount_path: /data1
      - disk: sdc
        vg_name: data2_vg
        lvm_name: data2_lv
        fs_type: ext4
        mount_path: /data2
    move_system_dir_config:
      - source: /var
        dest: /data1
        excludes:
          - /lib
          - /snap
      - source: /var/lib
        dest: /data2
  roles:
    - configure_lvm_and_fs
    - move_system_dir